### ISSUE TITLE
Request for option to display nickname

### ISSUE THREAD

**Issue by tparki** [JustCarmen/fancy_treeview#28]
When the tree contains numerous people with the same given and surnames it would help to be able to include nicknames in the report.

**Comment by JustCarmen** [comment]
This is already default behavior. If you have entered the information in your Gedcom like this:

1 NAME John /Doe/
2 GIVN John
2 NICK Johnny
2 SURN Doe

The name will be outputted on the Fancy Treeview page as: John "Johnny" Doe
