### ISSUE TITLE
Fancy_treeview with Xeno theme

### ISSUE THREAD

**Issue by rbur** [JustCarmen/fancy_treeview#29]
I am trying to use with the Xeno theme which is an adaptation of the Xenea theme. The menu icon is incorrect compared to other themes. I tried using a copy of the Xenea theme and renamed to Xeno in the modules_v3/fancy_treeview/themes but that did not work.
Is there a suggestion ??

This is with Xeno
![fancy-view](https://cloud.githubusercontent.com/assets/5042056/5675006/34c6ada0-977a-11e4-9ee0-8155584656ab.jpg)

This is with Xena
![fancy-view2](https://cloud.githubusercontent.com/assets/5042056/5675050/15bee85e-977b-11e4-9f64-d58b032d58da.jpg)

thanks ... Ron

**Comment by JustCarmen** [comment]
I thought the theme was called Xeneo and not Xeno. Because you did the right thing by copying the xenea folder. But the copied folder must have the exact same name as the main theme. So I think you need to check the name of the folder.
