### ISSUE TITLE
JustLight theme option module error

### ISSUE THREAD

**Issue by wooc** [JustCarmen/fancy_treeview#31]
Call to a member function addInlineJavascript() on a non-object in \modules_v3\fancy_treeview\fancytreeview.php on line 1051

**Comment by JustCarmen** [comment]
Does this error occur in the latest release (1.6.2) or in the dev version? And can you tell me when you get this error? On the config page? On the Fancy Treeview Page or on any other page?

**Comment by wooc** [comment]
Dev version
I see it on the justlight theme options module config page
Page: module.php?mod=justlight_theme_options&mod_action=admin_config
