### ISSUE TITLE
Using of AFT

### ISSUE THREAD

**Issue by MrRux** [JustCarmen/fancy_treeview#32]
If I use AFT 1939, Fancy_treeview produced this string:

", was born on 9 February 1927 in Berlin Stadt, Brandenburg, Preußen, Deutsches Reich and died after 1939 at the age of 11. "
This person died years past this date, but it is the last date I have a prove for

I think, it is better not to print the concrete age, if the format AFT is in use.

**Comment by JustCarmen** [comment]
I think you are right. But I think this counts not only for AFT but also for some of the other date qualifiers. I will look into it.
