### ISSUE TITLE
Change root person

### ISSUE THREAD

**Issue by HRN-webtrees** [JustCarmen/fancy_treeview#33]
Change root person doesn't work. Adding ID or searching by name takes me to "My page"

**Comment by JustCarmen** [comment]
Are you using the latest (development) versions of both webtrees and this module?

I don't have any problems adding a start person by ID or Name, so I'm afraid I can't reproduce the problem. Do you have more information like an error log or something?

**Comment by HRN-webtrees** [comment]
Latest versions of both. Tested again, and found it to be theme related. Change root person does not work in colors and clouds themes.

**Comment by JustCarmen** [comment]
I have found the problem. It turned out to be an error in one of the core webtrees files. I just provided a patch to solve this.

https://github.com/fisharebest/webtrees/pull/493

**Comment by JustCarmen** [comment]
The scripts within the module were in conflict with the webtrees.js script. Changing the module scripts also solves the problem.
