### ISSUE TITLE
Prefix before placenames

### ISSUE THREAD

**Issue by JustCarmen** [JustCarmen/fancy_treeview#36]
Request received by email:

> The string [before placenames] is represented with only one alternativ: in (english), i (norw.bokmål, danish, swedish)
In norwegian we use two words: i and på. Fluent norwegian would be i Bergen (name of towns), but på Kleiveland (name of farms). I'm working mostly with families from rural Norway, therefore I've chosen på in this string. Ideally there should have been two alternatives.....

This refers to the Norwegian Nynorsk translation (nn.po).

**Comment by JustCarmen** [comment]
It is not possible to implement this. There is no way the script could know when the placename refers to a town and when it refers to a farm.

**Comment by HRN-webtrees** [comment]
As you said, there is no way the script could know when the placename refers to a town and when it refers to a farm. Also there are many exeptions to this "rule".

The genealogy software Embla has solved this by allowing you to add and store corresponding preposition (or short phrase like "on the farm") to the DB when entering a place name,
thus alternative preposition (if found in DB) is used in reports.

Would it be possible to add this feature to webtrees?

**Comment by JustCarmen** [comment]
I've seen you have also asked this question at the webtrees forum which is the right place to go to, because the change you want requires a change in the webtrees core. As soon as Greg decides to implement this feature I can use it inside this module. So it depends on the outcome of this discussion:
https://www.webtrees.net/index.php/en/forum/9-request-for-new-feature/30853-place-names#56454

**Comment by HRN-webtrees** [comment]
Yes, i realised that this would imply changes in the core, and therefore asked at webtrees forum.
I hope Greg will find time to do this, though probably not first priority....
