### ISSUE TITLE
Question...No Issue.

### ISSUE THREAD

**Issue by FP2006** [JustCarmen/fancy_treeview#37]
First, I wanted to say thank you.  We have been looking for a Treeview with great performance and features and found several with one or the other, but none with both...unitl Fancy_Treeview.

I am a non-developer and trying to learn more about the capabilities. In our application we require a lot of "batch" node and leaf options like, selecting/unselecting all the lowest level leafs in a branch, selecting/unselecting all of children in a branch.  I have found demos where we can select or unselect all items.  I am curious if there are demos that focus those on a specific branch.

Our data is such that we can have the same item appear in multiple branches.  Ideally when we select the item in branch 1 we would like it to be auto-selected throughout the rest of the tree.  Are we dreaming?

Thanks in advance for helping me better understand the capabilities!

**Comment by JustCarmen** [comment]
I don't know if I understand you completely but I think I do but please forgive me if I am wrong.

I think I can illustrate it the best with an example of my own family tree site.

In my main tree I have set two Fancy Treeview branches. The individuals to focus on are the individuals listed from generation 5 in this branch:

http://wijzijnfamilie.nl/module.php?mod=fancy_treeview&mod_action=page&rootid=I1020

The same individuals you will find in this branch:
http://wijzijnfamilie.nl/module.php?mod=fancy_treeview&mod_action=page&rootid=I1993

You will find these individuals in this branch from generation 12.

For example person 5.1 in the first branch is the same person as 12.3 in the second branch.

Is this what you mean?

**Comment by FP2006** [comment]
Yes,  if your control was setup with checkboxes to select and unselect people...if we selected the person from 5.1 we would want to automatically make sure the are selected in 12.3 as well.  I am trying to figure out of there a way to make this happen (or facilitate it) or if we need to write our own code to search the tree and mark them.

Thanks!

**Comment by JustCarmen** [comment]
The treeview is controlled by rootpersons. You set a rootperson and all descendants of this rootperson are listed in the tree. In the example above the root person of the first branch has the ID I1020 (see the last part of the url). The root person in the second branch has the ID I1993,

The person in my example (5.1/12.3) is a descendant of both.

In the configuration settings these two root persons are set as starting point. The Fancy Treeview is only able to list descendants, I think you rather want to turn the tree upside down and list the ancestors... (person 5.1/12.3 has ancestors in two different branches, but the same descendants). 
Unfortunately that is not possible right now.

**Comment by FP2006** [comment]
Thanks for the help!  I was looking more into the control and read something a "clone extension".  To a non-programmer it looks like that extension may allow us to scan an entire tree and return "matching" nodes to any node we enter.  Have you leveraged the Clone Extension?  If so, is my understanding totally off?

**Comment by JustCarmen** [comment]
I think you don't understand the purpose of this module. This is a module for [webtrees](https://github.com/fisharebest/webtrees), a genealogical program. It can only be used in combination with this program. I don't think this is what you are looking for, right?

**Comment by FP2006** [comment]
My apologies.  I was looking for more info on the "FancyTree" jQuery control.  Thanks.

**Comment by JustCarmen** [comment]
Never mind. Can happen. I wasn't even aware of the existence of this jQuery plugin with almost the same name ;).
