### ISSUE TITLE
*.mo files outdated

### ISSUE THREAD

**Issue by magicsunday** [JustCarmen/fancy_treeview#44]
Please update to *.mo files on a regular basis.

**Comment by mpwt** [comment]
I sent a new german translation to Carmen today. I have changed something, translated untranslated strings and added one missing string:

#. I18N: Help text for the “Show Fancy Treeview on Indi Page” configuration setting
#: fancy_treeview/src/Template/AdminTemplate.php:500
msgid "If you enable this option, a Fancy Treeview tab with the title ’Descendants’ will be shown on the individual page. The tab will describe the current individual with his family and the next two generations (if there are any). If this persons has more descendants then the two generations shown, a link will be displayed to the full Fancy Treeview Page with this person as root person and all his descendants."
msgstr "Wenn Sie diese Option aktivieren wird auf der Personenseite ein Reiter mit dem Titel ’Nachkommen’ angezeigt. Hier wird die aktuelle Person mit ihrer Familie und den nächsten zwei Generationen (falls solche vorhanden sind) beschrieben. Wenn diese Person mehr Nachkommen als die angezeigten zwei Generationen hat, wird ein Link zur kompletten Nachkommenliste mit dieser Person als Startperson und allen Nachkommen angezeigt. <b>Hinweis</b>: Wenn das Erweiterungsmodul Fancy Treeview PDF installiert und aktiviert ist, kann dort ein Link zum Herunterladen der kompletten Nachkommenliste als PDF-Datei angezeigt werden."

I hope that is what you was looking for.

**Comment by JustCarmen** [comment]
The file is updated now. Thanks.
