### ISSUE TITLE
PDF export using webtrees system exporter

### ISSUE THREAD

**Issue by imskriaz** [JustCarmen/fancy_treeview#45]
Fancy Treeview is really a best module for Webtrees.

I believe Webtrees has its own coding to export PDF. Is their any possibility to use that resources and omit additional module requirement to generate pdf from Tree View.

**Comment by JustCarmen** [comment]
No, I am sorry. Believe me I've tried this in the past. webtrees uses TCPDF as pdf system. TCPDF can't handle stylesheets. I need the stylesheets to style the PDF's the way they are now. Another issue is the report system in webtrees is based on reports written in xml. I use a different approach by taking the content from the existing webpage itself (the fancy treeview page), This means I should have written my own system anyway and therefore mpdf was a much easier solution.
