### ISSUE TITLE
Fatal error after upgrade to 1.7.5

### ISSUE THREAD

**Issue by tronsmit** [JustCarmen/fancy_treeview#47]
Upgraded to 1.7.5 (auto), chose the [disable these modules] option.

I have the following custom modules:
fancy{branches, imagebar, privacy_list, research_links, treeview, treeview_pdf, justlight_theme_options} - really good tools!
and one of my own

After the successful upgrade message, I clicked on "my page" link and received the following message, which of course persisted and did not allow access to the site.

**Fatal error: Call to a member function getTreeId() on null in .../modules_v3/fancy_treeview/module.php on line 66**

It was fixed, by deleting the folder fancy_treeview on the server, then accessing the site again - now OK, then reinstalling fancy_treeview (the same version, from the zip, fetched from the installation site today).

**Comment by JustCarmen** [comment]
Hi, I have just added a new release. It was already fixed in development version but now the latest release also contains the fix.

https://github.com/JustCarmen/fancy_treeview/releases/tag/1.7.5
