### ISSUE TITLE
Flowing text wrong

### ISSUE THREAD

**Issue by geheme** [JustCarmen/fancy_treeview#48]
In visitor mode of flowing text is not appended to the Image.

![fancy_wrong](https://cloud.githubusercontent.com/assets/20037372/16184564/980ea6ea-36bd-11e6-8eec-10f660169048.JPG)

The text is displayed correctly in logon mode

![fancy_ok](https://cloud.githubusercontent.com/assets/20037372/16184576/add6f590-36bd-11e6-8520-8439cd7dec18.JPG)

**Comment by JustCarmen** [comment]
I see I forgot to close this issue. This is already solved with commit https://github.com/JustCarmen/fancy_treeview/commit/5545980a5b652ea0c5e293a3f3647a044c87b981 and added to release 1.7.5.
