### ISSUE TITLE
"... follow x.y" in PDF is missing

### ISSUE THREAD

**Issue by jpretired** [JustCarmen/fancy_treeview#52]
If 'Number of generation blocks to show' option is set to less than 'All' (i.e. 1 to 10)
then
"... follow x.y" in PDF is missing.
**On screen:**
![vyber_024](https://cloud.githubusercontent.com/assets/350656/22981301/5c7171b6-f39c-11e6-9254-3516e51287ac.png)
**In PDF:**
![vyber_025](https://cloud.githubusercontent.com/assets/350656/22981434/b02b33b4-f39c-11e6-9a93-eed72f7b1b9a.png)

If the option is set to 'All' then the PDF is correct:
![vyber_026](https://cloud.githubusercontent.com/assets/350656/22981666/4d587e6c-f39d-11e6-907a-37f3b1f5c54a.png)

**Comment by JustCarmen** [comment]
This is a bug indeed. I am working on a solution.

**Comment by jpretired** [comment]
Now it works OK. Thank you JustCarmen.
