### ISSUE TITLE
The file Descendants of Johann Jacob Rux.pdf could not be created.

### ISSUE THREAD

**Issue by MrRux** [JustCarmen/fancy_treeview#66]
webtrees 1.7.9, Fancy Treeview Version 1.7.9, Fancy Treeview PDF Version 1.7.9.1, PHP Version 7.1.13

I deleted the previous folders (Treeview and PDF) and intalled them new, Treeview works fine, but every times, I click on the pdf-button, i will get this error-message:
The file Descendants of Johann Jacob Rux.pdf could not be created.

It worked some Versions before, but I dont use the pdf option a lot.

**Comment by JustCarmen** [comment]
Hi, please try the latest release of fancy treeview pdf. This should solve your issue.
