### ISSUE TITLE
I can not create pdf in webtrees

### ISSUE THREAD

**Issue by JohnnyD1963** [JustCarmen/fancy_treeview#67]
Hope some one can help me to fix this i see only on the page.
`/var/www/html/includes/session.php:193 /var/www/html/vendor/tecnickcom/tcpdf/tcpdf.php:16542 The each() function is deprecated. This message will be suppressed on further calls #0 unknown:unknown ErrorException("/var/www/html/vendor/tecnickcom/tcpdf/tcpdf.php:16542 The each() function is deprecated. This message will be suppressed on further calls") #1 /vendor/tecnickcom/tcpdf/tcpdf.php:16542 each([array]) #2 /vendor/tecnickcom/tcpdf/tcpdf.php:17199 getHtmlDomArray('Afstammelinge…') #3 /vendor/tecnickcom/tcpdf/tcpdf.php:5828 writeHTML('Afstammelinge…', true, false, true, true, 'C') #4 /app/Report/ReportPdfCell.php:127 MultiCell(516.28, 30, 'Afstammelinge…', 0, 'C', 0, 1, 51.0, 14.0, true, 0, true) #5 /app/Report/ReportTcpdf.php:62 render([ReportTcpdf]) #6 /vendor/tecnickcom/tcpdf/tcpdf.php:3537 header() #7 /vendor/tecnickcom/tcpdf/tcpdf.php:3204 setHeader() #8 /vendor/tecnickcom/tcpdf/tcpdf.php:3116 startPage('', '', false) #9 /app/Report/ReportTcpdf.php:84 AddPage() #10 /app/Report/ReportPdf.php:128 body() #11 /app/Report/ReportParserGenerate.php:332 run() #12 /app/Report/ReportParserGenerate.php:179 docEndHandler() #13 unknown:unknown endElement([resource], 'Doc') #14 /app/Report/ReportParserBase.php:43 xml_parse([resource], 'xtBox>`

Can someone help me ?

**Comment by JohnnyD1963** [comment]
I think i have to wait for an update of webtrees i just readed in webtrees forum that the last webtrees is made before php 7.2.

**Comment by JustCarmen** [comment]
Hi, please try the latest release of [fancy treeview pdf](https://github.com/JustCarmen/fancy_treeview_pdf/releases/tag/1.7.11). This should solve your issue.
